version: '3.8'

services:
  nsh-chengyu:
    build: .
    ports:
      - "8666:8666"
    environment:
      - FLASK_ENV=production
      - PORT=8666
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8666/"]
      interval: 30s
      timeout: 10s
      retries: 3