name: auto

on:
  repository_dispatch:
  workflow_dispatch:
  #  schedule:
  #    - cron: '0 18 * * 5'
  #  watch:
  #    types: started

  # on:
  #   push:
  #     branches:
  #       - master # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t mdespot/nsh_chy:${{ github.sha }} .
          docker tag mdespot/nsh_chy:${{ github.sha }} mdespot/nsh_chy:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push mdespot/nsh_chy:latest
          docker push mdespot/nsh_chy:${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker pull mdespot/nsh_chy:${{ github.sha }}
            docker stop nsh_chy || true
            docker rm nsh_chy || true
            docker run -d --name nsh_chy -p 8666:8666 --health-cmd="curl -f http://localhost:8666/ || exit 1" --health-interval=30s --health-timeout=10s --health-retries=3 mdespot/nsh_chy:${{ github.sha }}
